### ISSUE TITLE
[Version 1.0.2] TypeError: The "data" argument must be of type string or an instance of Buffer

### ISSUE THREAD

**Issue by homestar9** [michtio/laravel-mix-criticalcss#23]
I started getting the following error today when trying to use the Laravel Mix CriticalCSS plugin on Node.js v18.17.1

`npm run prod` produces:

```
● Mix █████████████████████████ emitting (98%) after emit
 HtmlCriticalWebpackPlugin

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2271:5)
    at go$writeFile (D:\my-project\node_modules\graceful-fs\graceful-fs.js:138:14)
    at Object.writeFile (D:\my-project\node_modules\graceful-fs\graceful-fs.js:135:12)        
    at D:\my-project\node_modules\critical\node_modules\fs-extra\lib\output\index.js:18:27    
    at D:\my-project\node_modules\universalify\index.js:23:46 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by homestar9** [comment]
This was my error.  If one of the URLs in your critical CSS configuration is missing or throws an exception, you will get the error mentioned in my original post.

For example:
```
mix.criticalCss({
    enabled: mix.inProduction(),
    paths: {
        base: 'http://127.0.0.1:' + commandboxPort + '/',
        templates: './includes/css/',
        suffix: '.critical'
    },
    urls: [
        { url: '/', template: 'main.index' },
        { url: '/contact', template: 'content.show' }, <-- this URL returns a 404
    ],
    options: {
        width:411,
        height:823,
        penthouse:{
            timeout:1200000
        }
    },
});
```

Removing the broken link fixed the error. I hope this helps anyone else that stumbles across this one.
